export default function useProjects() {
  return [
    {
      title: "Gifted",
      badge: "Web App",
      technologies: "NextJS • React • TailwindCSS",
      bgClassName: "bg-gifted",
      siteLink: "https://getgifted.app",
    },
    {
      title: "Luke Ivie",
      badge: "This Site",
      isMainBadge: true,
      technologies: "NextJS • React • TailwindCSS",
      bgClassName: "bg-lukeivie",
      siteLink: "https://lukeivie.com",
      githubLink: "https://github.com/lukeivie/lukeivie.com",
    },
    {
      title: "DiscountMags.com",
      badge: "Website",
      showSiteLinkIcon: true,
      technologies: "Typescript • PHP • NextJS",
      bgClassName: "bg-discountmags",
      siteLink: "https://discountmags.com",
    },
    {
      title: "Openforce",
      badge: "Website",
      showSiteLinkIcon: true,
      technologies: "Wordpress • Bootstrap 4",
      bgClassName: "bg-openforce",
      siteLink: "https://oforce.com",
    },
    {
      title: "Tanga Redesign",
      badge: "Website",
      technologies: "React • Bootstrap 4",
      bgClassName: "bg-tangaredesign",
      siteLink: "https://tanga-redesign-fooj7cp47-latenightluke.vercel.app/",
      githubLink: "https://github.com/lukeivie/tanga-redesign",
    },
    {
      title: "YL Pool Party",
      badge: "Website",
      technologies: "HTML • Javascript • Bootstrap 4",
      bgClassName: "bg-ylpoolparty",
      siteLink: "https://ylpool.party",
      githubLink: "https://github.com/lukeivie/ylpoolparty",
    },
    {
      title: "Young Luke",
      badge: "Website",
      technologies: "React • Bootstrap 4",
      bgClassName: "bg-younglukemusic",
      siteLink: "https://younglukemusic.com",
    },
    {
      title: "911FosterPets",
      badge: "Website & Web App",
      technologies: "React • Bootstrap 4",
      bgClassName: "bg-911fosterpets",
      siteLink: "https://911fosterpets.com/",
    },
  ];
}
