export default function useTechnologies() {
  return [
    "Typescript",
    "NextJS",
    "React",
    "TailwindCSS",
    "Javascript",
    "Node",
    "Express",
    "Redux",
    "REST",
    "GraphQL",
    "MongoDB",
    "PostgreSQL",
    "HTML",
    "CSS",
    "SCSS",
    "Elixir",
    "C#",
    "PHP",
    "Bootstrap",
    "JQuery",
    "Wordpress",
    "Figma",
    "Sketch",
    "Photoshop",
  ];
}
