import { library } from "@fortawesome/fontawesome-svg-core";

import {
  faSaxophone,
  faMoon as fasMoon,
  faSunHaze as fasSunHaze,
  faLightbulb as fasLightbulb,
  faLightbulbOn as fasLightbulbOn,
  faCity as fasCity,
  faHouse as fasHouse,
  faBriefcase as fasBriefcase,
  faTools as fasTools,
  faFileAlt as fasFileAlt,
  faHotel as fasHotel,
  faLaptopCode as fasLaptopCode,
  faSunset as fasSunset,
  faSun as fasSun,
  faSunglasses as fasSunglasses,
} from "@fortawesome/pro-solid-svg-icons";

import {
  faLongArrowAltRight,
  faLongArrowAltLeft,
  faMoon,
  faCity,
  faSun,
  faSunHaze,
  faSunglasses,
  faEnvelope,
  faBuilding,
  faBlog,
  faTools,
  faBook,
  faLightbulb,
  faLongArrowRight,
  faLongArrowLeft,
  faLongArrowDown,
  faLongArrowUp,
  faInfoCircle,
  faExternalLink,
  faBriefcase,
  faAngleDown,
  faHotel,
} from "@fortawesome/pro-regular-svg-icons";

import {
  faHouse as falHouse,
  faBriefcase as falBriefcase,
  faTools as falTools,
  faFileAlt as falFileAlt,
  faHotel as falHotel,
  faLaptopCode as falLaptopCode,
  faSunset as falSunset,
  faSun as falSun,
  faSunglasses as falSunglasses,
} from "@fortawesome/pro-light-svg-icons";

import {
  faGithub,
  faTwitter,
  faLinkedin,
} from "@fortawesome/free-brands-svg-icons";

library.add(
  falSunglasses,
  fasSunglasses,
  falSun,
  fasSun,
  fasSunset,
  falSunset,
  falLaptopCode,
  fasLaptopCode,
  falHotel,
  faHotel,
  fasHotel,
  faAngleDown,
  fasFileAlt,
  falFileAlt,
  faExternalLink,
  fasTools,
  falTools,
  fasBriefcase,
  faBriefcase,
  falBriefcase,
  fasHouse,
  falHouse,
  faInfoCircle,
  fasCity,
  faLongArrowRight,
  faLongArrowLeft,
  faLongArrowDown,
  faLongArrowUp,
  faLightbulb,
  fasLightbulb,
  fasLightbulbOn,
  faBook,
  faTools,
  faBlog,
  faMoon,
  fasMoon,
  faSun,
  fasSunHaze,
  faCity,
  faSaxophone,
  faBuilding,
  faSunHaze,
  faSunglasses,
  faLongArrowAltRight,
  faLongArrowAltLeft,
  faGithub,
  faTwitter,
  faLinkedin,
  faEnvelope
);
